-- BU SQL'İ SUPABASE SQL EDITOR'DE ÇALIŞTIRIN --

CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action text not null, -- Örn: 'CREATE_AD', 'BAN_USER'
  metadata jsonb default '{}'::jsonb, -- Detaylı veri
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Okuma izni (Sadece adminler okuyabilir - RLS politikası eklenebilir)
alter table audit_logs enable row level security;

create policy "Adminler logları görebilir"
  on audit_logs for select
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );