-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Favoriler Tablosu
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  ad_id bigint references ads(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Bir kullanıcı aynı ilanı sadece bir kez favorileyebilir
  unique(user_id, ad_id)
);

-- 2. İndeksler (Performans için)
create index if not exists idx_favorites_user_id on favorites(user_id);
create index if not exists idx_favorites_ad_id on favorites(ad_id);

-- 3. RLS (Güvenlik Politikaları)
alter table favorites enable row level security;

-- Okuma: Kullanıcı sadece kendi favorilerini görebilir
create policy "Users can view their own favorites"
  on favorites for select
  using (auth.uid() = user_id);

-- Ekleme: Kullanıcı sadece kendine favori ekleyebilir
create policy "Users can add their own favorites"
  on favorites for insert
  with check (auth.uid() = user_id);

-- Silme: Kullanıcı sadece kendi favorisini silebilir
create policy "Users can delete their own favorites"
  on favorites for delete
  using (auth.uid() = user_id);

-- 4. Realtime (Anlık Güncelleme için)
-- Eğer realtime açık değilse tabloyu yayına ekle
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and tablename = 'favorites'
  ) then
    alter publication supabase_realtime add table favorites;
  end if;
end
$$;