-- BU KODU SUPABASE SQL EDITOR'DE ÇALIŞTIRIN --

-- 1. ADS Tablosunu Garantiye Al (Eksikse Oluştur)
CREATE TABLE IF NOT EXISTS ads (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  title text not null,
  description text,
  price numeric,
  currency text default 'TL',
  city text,
  district text,
  category text,
  image text,
  images text[],
  status text default 'onay_bekliyor',
  is_vitrin boolean default false,
  is_urgent boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Eksik Sütunları Ekle (Vasıta ve Emlak İçin)
-- Bu komutlar sütun yoksa ekler, varsa hata vermez.

-- Emlak Sütunları
ALTER TABLE ads ADD COLUMN IF NOT EXISTS m2 numeric;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS room text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS floor numeric;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS heating text;

-- Vasıta Sütunları
ALTER TABLE ads ADD COLUMN IF NOT EXISTS brand text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS model text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS year numeric;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS km numeric;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS gear text; -- Vites
ALTER TABLE ads ADD COLUMN IF NOT EXISTS fuel text; -- Yakıt

-- Moderasyon ve Sistem Sütunları (Önceki adımda eksik kalmış olabilir)
ALTER TABLE ads ADD COLUMN IF NOT EXISTS moderation_score integer default 0;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS moderation_tags text[] default '{}';
ALTER TABLE ads ADD COLUMN IF NOT EXISTS admin_note text;
ALTER TABLE ads ADD COLUMN IF NOT EXISTS view_count integer default 0;

-- 3. RLS (Güvenlik) İzinlerini Yenile
-- İlan eklerken "Permission Denied" hatası almamak için.
ALTER TABLE ads ENABLE ROW LEVEL SECURITY;

-- Mevcut politikaları temizle (Çakışmayı önlemek için)
DROP POLICY IF EXISTS "Herkes ilanları görebilir" ON ads;
DROP POLICY IF EXISTS "Kullanıcılar ilan ekleyebilir" ON ads;
DROP POLICY IF EXISTS "Kullanıcılar kendi ilanlarını düzenleyebilir" ON ads;

-- Yeni politikalar
CREATE POLICY "Herkes ilanları görebilir"
  ON ads FOR SELECT
  USING (true);

CREATE POLICY "Kullanıcılar ilan ekleyebilir"
  ON ads FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Kullanıcılar kendi ilanlarını düzenleyebilir"
  ON ads FOR UPDATE
  USING (auth.uid() = user_id);

-- 4. Şema Önbelleğini Yenile (Çok Önemli!)
-- Supabase API'sinin yeni sütunları görmesi için bunu çalıştırmak şarttır.
NOTIFY pgrst, 'reload schema';