-- BU KODU SUPABASE SQL EDITOR'DE ÇALIŞTIRIN --

-- 1. Cüzdanlar Tablosu (Her kullanıcının 1 cüzdanı olur)
CREATE TABLE IF NOT EXISTS wallets (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  balance decimal(10, 2) default 0.00 check (balance >= 0),
  currency text default 'TL',
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. İşlemler Tablosu (Para giriş/çıkış kayıtları - Ledger)
CREATE TABLE IF NOT EXISTS transactions (
  id bigint generated by default as identity primary key,
  wallet_id bigint references wallets(id) not null,
  type text not null check (type in ('deposit', 'spend', 'refund')), -- Para Yükleme, Harcama, İade
  amount decimal(10, 2) not null,
  description text,
  reference_id text, -- Örn: İlan ID'si veya Ödeme Sağlayıcı ID'si
  status text default 'completed',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. Kullanıcı oluştuğunda otomatik cüzdan oluşturan Trigger
create or replace function public.handle_new_user_wallet()
returns trigger as $$
begin
  insert into public.wallets (user_id)
  values (new.id);
  return new;
end;
$$ language plpgsql security definer;

-- Trigger'ı bağla (Eğer profiles trigger'ı varsa ona entegre edilebilir, yoksa ayrı çalışır)
-- drop trigger if exists on_auth_user_created_wallet on auth.users;
-- create trigger on_auth_user_created_wallet
--   after insert on auth.users
--   for each row execute procedure public.handle_new_user_wallet();

-- Manuel Cüzdan Oluşturma (Mevcut kullanıcılar için)
INSERT INTO wallets (user_id)
SELECT id FROM auth.users
ON CONFLICT (user_id) DO NOTHING;