-- BU KODU SUPABASE SQL EDITOR'DE ÇALIŞTIRIN --

-- 1. Tabloyu Sıfırdan Temizle (Hatalı ilişkileri düzeltmek için)
-- Not: Mevcut favoriler silinecektir, ancak sistemin çalışması için bu gereklidir.
DROP TABLE IF EXISTS favorites CASCADE;

-- 2. Tabloyu Yeniden Oluştur (Doğru İlişkilerle)
CREATE TABLE favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  ad_id bigint references ads(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Çifte kayıt önleme
  unique(user_id, ad_id)
);

-- 3. RLS (Güvenlik) Politikalarını Tanımla
ALTER TABLE favorites ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own favorites"
  ON favorites FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can add their own favorites"
  ON favorites FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can delete their own favorites"
  ON favorites FOR DELETE
  USING (auth.uid() = user_id);

-- 4. İlanları Okuma İzni (Favorilerde ilan detaylarını çekebilmek için kritik)
DROP POLICY IF EXISTS "Herkes ilanları görebilir" ON ads;
CREATE POLICY "Herkes ilanları görebilir"
ON ads FOR SELECT
USING (true);

-- 5. Cache Temizle
NOTIFY pgrst, 'reload schema';