-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. ADS (İLANLAR) TABLOSU İZİNLERİNİ AÇ --
-- Eğer ilanları okuma izni yoksa, favorilerde ilan detayları 'null' gelir.
alter table ads enable row level security;

-- Eski politikaları temizle (Çakışmayı önlemek için)
drop policy if exists "Herkes ilanları görebilir" on ads;
drop policy if exists "Ads are viewable by everyone" on ads;
drop policy if exists "Public read access" on ads;

-- Yeni Geniş Kapsamlı Okuma Politikası
create policy "Herkes ilanları görebilir"
on ads for select
using (true);

-- 2. FAVORITES TABLOSUNU SAĞLAMLAŞTIR --
-- Tablo yoksa oluştur
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  ad_id bigint references ads(id) on delete cascade not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, ad_id)
);

-- RLS Politikalarını Yenile
alter table favorites enable row level security;

drop policy if exists "Users can view their own favorites" on favorites;
drop policy if exists "Users can add their own favorites" on favorites;
drop policy if exists "Users can delete their own favorites" on favorites;

create policy "Users can view their own favorites"
  on favorites for select
  using (auth.uid() = user_id);

create policy "Users can add their own favorites"
  on favorites for insert
  with check (auth.uid() = user_id);

create policy "Users can delete their own favorites"
  on favorites for delete
  using (auth.uid() = user_id);

-- 3. İLİŞKİLERİ KONTROL ET (Foreign Key) --
-- Supabase'in 'ads' tablosunu otomatik tanıması için FK şarttır.
-- Eğer daha önce FK oluşturulmadıysa hata vermemesi için güvenli blok:
do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_name = 'favorites_ad_id_fkey'
  ) then
    alter table favorites add constraint favorites_ad_id_fkey
    foreign key (ad_id) references ads(id) on delete cascade;
  end if;
end
$$;