-- BU DOSYAYI SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. FAVORİLER TABLOSU
create table if not exists favorites (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  ad_id bigint references ads(id) not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(user_id, ad_id)
);

alter table favorites enable row level security;

create policy "Kullanıcılar kendi favorilerini görebilir" on favorites for select using (auth.uid() = user_id);
create policy "Kullanıcılar favori ekleyebilir" on favorites for insert with check (auth.uid() = user_id);
create policy "Kullanıcılar favori silebilir" on favorites for delete using (auth.uid() = user_id);

-- 2. MESAJLAŞMA SİSTEMİ
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  ad_id bigint references ads(id) not null,
  buyer_id uuid references auth.users not null,
  seller_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(ad_id, buyer_id, seller_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations(id) on delete cascade not null,
  sender_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table conversations enable row level security;
alter table messages enable row level security;

create policy "Sohbet Görüntüleme" on conversations for select using (auth.uid() = buyer_id or auth.uid() = seller_id);
create policy "Sohbet Başlatma" on conversations for insert with check (auth.uid() = buyer_id);

create policy "Mesaj Görüntüleme" on messages for select using (
  exists (select 1 from conversations c where c.id = messages.conversation_id and (c.buyer_id = auth.uid() or c.seller_id = auth.uid()))
);
create policy "Mesaj Gönderme" on messages for insert with check (auth.uid() = sender_id);
create policy "Mesaj Okundu" on messages for update using (
  exists (select 1 from conversations c where c.id = messages.conversation_id and (c.buyer_id = auth.uid() or c.seller_id = auth.uid()))
);

alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table conversations;

-- 3. AUDIT LOGS
CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action text not null,
  metadata jsonb default '{}'::jsonb,
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);
alter table audit_logs enable row level security;
create policy "Admin Read" on audit_logs for select using (exists (select 1 from profiles where profiles.id = auth.uid() and profiles.role = 'admin'));
create policy "System Write" on audit_logs for insert with check (auth.uid() = user_id);