-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Sohbetler Tablosu (Conversations)
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  ad_id bigint references ads(id) not null,
  buyer_id uuid references auth.users not null,
  seller_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Aynı ilan için aynı alıcı ve satıcı arasında tek bir sohbet olabilir
  unique(ad_id, buyer_id, seller_id)
);

-- 2. Mesajlar Tablosu (Messages)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations(id) on delete cascade not null,
  sender_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. RLS (Row Level Security) Politikaları - GÜVENLİK İÇİN KRİTİK
alter table conversations enable row level security;
alter table messages enable row level security;

-- Sohbetleri sadece katılımcıları görebilir
create policy "Users can view their own conversations"
  on conversations for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

create policy "Users can insert conversations"
  on conversations for insert
  with check (auth.uid() = buyer_id);

-- Mesajları sadece sohbetin katılımcıları görebilir (JOIN ile kontrol)
create policy "Users can view messages in their conversations"
  on messages for select
  using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

create policy "Users can insert messages"
  on messages for insert
  with check (auth.uid() = sender_id);

create policy "Users can update read status"
  on messages for update
  using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

-- 4. Realtime Yayın
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table conversations;