-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Tabloları Oluştur (Eğer yoksa)
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  ad_id bigint references ads(id) not null,
  buyer_id uuid references auth.users not null,
  seller_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,
  unique(ad_id, buyer_id, seller_id)
);

create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations(id) on delete cascade not null,
  sender_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. RLS Aktifleştir
alter table conversations enable row level security;
alter table messages enable row level security;

-- 3. ESKİ POLİTİKALARI TEMİZLE (Hata almamak için)
drop policy if exists "Users can view their own conversations" on conversations;
drop policy if exists "Users can insert conversations" on conversations;
drop policy if exists "Users can update conversations" on conversations;
drop policy if exists "Users can start conversations" on conversations; -- Eski isim olasılığına karşı

drop policy if exists "Users can view messages in their conversations" on messages;
drop policy if exists "Users can insert messages" on messages;
drop policy if exists "Users can update read status" on messages;

-- 4. YENİ POLİTİKALARI OLUŞTUR

-- Sohbetler: Okuma
create policy "Users can view their own conversations"
  on conversations for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

-- Sohbetler: Ekleme (Başlatma)
create policy "Users can insert conversations"
  on conversations for insert
  with check (auth.uid() = buyer_id);

-- Sohbetler: Güncelleme
create policy "Users can update conversations"
  on conversations for update
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

-- Mesajlar: Okuma
create policy "Users can view messages in their conversations"
  on messages for select
  using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

-- Mesajlar: Ekleme
create policy "Users can insert messages"
  on messages for insert
  with check (auth.uid() = sender_id);

-- Mesajlar: Güncelleme (Okundu bilgisi için)
create policy "Users can update read status"
  on messages for update
  using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

-- 5. Realtime Yayın
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'messages') then
    alter publication supabase_realtime add table messages;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and tablename = 'conversations') then
    alter publication supabase_realtime add table conversations;
  end if;
end
$$;