-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Mağazalar Tablosu
create table if not exists stores (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null unique,
  name text not null,
  slug text not null unique,
  description text,
  phone text,
  location text,
  website text,
  image text, -- Logo
  banner text, -- Kapak Görseli
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. İndeksler
create index if not exists idx_stores_slug on stores(slug);
create index if not exists idx_stores_user_id on stores(user_id);

-- 3. RLS (Güvenlik)
alter table stores enable row level security;

-- Herkes mağazaları görebilir
create policy "Stores are viewable by everyone"
  on stores for select
  using (true);

-- Sadece kendi mağazasını ekleyebilir
create policy "Users can insert their own store"
  on stores for insert
  with check (auth.uid() = user_id);

-- Sadece kendi mağazasını güncelleyebilir
create policy "Users can update their own store"
  on stores for update
  using (auth.uid() = user_id);