const fs = require("fs");
const path = require("path");

const colors = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  cyan: "\x1b[36m",
  yellow: "\x1b[33m",
  bold: "\x1b[1m",
};

console.log(
  colors.cyan +
    colors.bold +
    "\n🚀 SENIOR UPGRADE V2: AUDIT LOGS, RATE LIMITING & SECURITY...\n" +
    colors.reset,
);

function writeFile(filePath, content) {
  const absolutePath = path.join(__dirname, filePath);
  const dir = path.dirname(absolutePath);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
  fs.writeFileSync(absolutePath, content.trim());
  console.log(
    `${colors.green}✔ Güncellendi/Oluşturuldu:${colors.reset} ${filePath}`,
  );
}

// =============================================================================
// 1. SUPABASE/AUDIT.SQL (LOG TABLOSU SQL)
// =============================================================================
const auditSqlContent = `
-- BU SQL'İ SUPABASE SQL EDITOR'DE ÇALIŞTIRIN --

CREATE TABLE IF NOT EXISTS audit_logs (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users not null,
  action text not null, -- Örn: 'CREATE_AD', 'BAN_USER'
  metadata jsonb default '{}'::jsonb, -- Detaylı veri
  ip_address text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Okuma izni (Sadece adminler okuyabilir - RLS politikası eklenebilir)
alter table audit_logs enable row level security;

create policy "Adminler logları görebilir"
  on audit_logs for select
  using (
    exists (
      select 1 from profiles
      where profiles.id = auth.uid() and profiles.role = 'admin'
    )
  );
`;
writeFile("supabase/audit.sql", auditSqlContent);

// =============================================================================
// 2. LIB/SUPABASE/SERVER.TS (STATIC CLIENT FIX & COOKIE HANDLING)
// =============================================================================
const supabaseServerContent = `
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'

// 1. DYNAMIC CLIENT (Kullanıcı işlemleri için - Cookie Kullanır)
export async function createClient() {
  const cookieStore = await cookies()

  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll()
        },
        setAll(cookiesToSet) {
          try {
            cookiesToSet.forEach(({ name, value, options }) =>
              cookieStore.set(name, value, options)
            )
          } catch {
            // Server Component içinde cookie set edilemez
          }
        },
      },
    }
  )
}

// 2. STATIC CLIENT (Cache işlemleri için - Cookie KULLANMAZ)
// unstable_cache içinde bunu kullanacağız.
export function createStaticClient() {
  return createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    {
      cookies: {
        getAll() {
          return []
        },
        setAll(cookiesToSet) {
        },
      },
    }
  )
}
`;
writeFile("lib/supabase/server.ts", supabaseServerContent);

// =============================================================================
// 3. LIB/LOGGER.TS (LOGLAMA SERVİSİ)
// =============================================================================
const loggerContent = `
import { createClient } from '@/lib/supabase/server';

/**
 * Kritik işlemleri veritabanına kaydeder.
 * @param userId İşlemi yapan kullanıcı
 * @param action İşlem tipi (örn: 'CREATE_AD')
 * @param metadata İşlem detayları
 */
export async function logActivity(userId: string, action: string, metadata: any = {}) {
  try {
    const supabase = await createClient();

    // Loglama işlemi ana akışı bloklamamalı (await kullanmıyoruz veya hata fırlatmıyoruz)
    const { error } = await supabase.from('audit_logs').insert({
      user_id: userId,
      action,
      metadata,
    });

    if (error) console.error('Audit log insert error:', error);
  } catch (error) {
    console.error('Audit log system error:', error);
  }
}
`;
writeFile("lib/logger.ts", loggerContent);

// =============================================================================
// 4. LIB/ACTIONS.TS (SENIOR REFACTOR - RATE LIMIT & LOGGING ENTEGRASYONU)
// =============================================================================
const actionsContent = `
'use server'
import { createClient, createStaticClient } from '@/lib/supabase/server'
import { revalidatePath, unstable_cache } from 'next/cache'
import { adSchema } from '@/lib/schemas'
import { logActivity } from '@/lib/logger' // Yeni Logger

// --- YARDIMCI: RATE LIMIT CHECK ---
async function checkRateLimit(userId: string, actionType: 'ad_creation' | 'review') {
    const supabase = await createClient();
    const oneDayAgo = new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString();

    if (actionType === 'ad_creation') {
        const { count } = await supabase.from('ads')
            .select('*', { count: 'exact', head: true })
            .eq('user_id', userId)
            .gte('created_at', oneDayAgo);

        // Günlük 5 ilan limiti
        if ((count || 0) >= 5) return false;
    }
    return true;
}

// --- YORUM SİSTEMİ ---
export async function createReviewAction(targetUserId: string, rating: number, comment: string, adId?: number) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    if (!user) return { error: 'Giriş yapmalısınız.' };
    if (user.id === targetUserId) return { error: 'Kendinize yorum yapamazsınız.' };

    const { error } = await supabase.from('reviews').insert([{
        target_user_id: targetUserId,
        reviewer_id: user.id,
        ad_id: adId,
        rating,
        comment
    }]);

    if (error) return { error: 'Yorum kaydedilemedi.' };

    // Logla
    await logActivity(user.id, 'CREATE_REVIEW', { targetUserId, rating });

    revalidatePath(\`/satici/\${targetUserId}\`);
    return { success: true };
}

export async function getSellerReviewsServer(targetUserId: string) {
    const supabase = await createClient();
    const { data } = await supabase
        .from('reviews')
        .select('*, reviewer:reviewer_id(full_name, avatar_url)')
        .eq('target_user_id', targetUserId)
        .order('created_at', { ascending: false });

    return data || [];
}

export async function getUserDashboardStats() {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return null;

    const { data: ads } = await supabase
        .from('ads')
        .select('status, view_count, price')
        .eq('user_id', user.id);

    return ads || [];
}

// --- STATIC DATA FETCHING ---
export const getCategoryTreeServer = unstable_cache(
  async () => {
    const supabase = createStaticClient(); // Static Client kullanıldı
    const { data } = await supabase.from('categories').select('*').order('title');
    if (!data) return [];
    const parents = data.filter(c => !c.parent_id);
    return parents.map(p => ({ ...p, subs: data.filter(c => c.parent_id === p.id) }));
  }, ['category-tree'], { revalidate: 3600 }
);

export async function getAdsServer(searchParams: any) {
  const supabase = await createClient()
  const page = Number(searchParams?.page) || 1;
  const limit = 20;
  const from = (page - 1) * limit;
  const to = from + limit - 1;

  let query = supabase.from('ads').select('*, profiles(full_name), categories(title)', { count: 'exact' }).eq('status', 'yayinda');

  if (searchParams?.q) query = query.ilike('title', \`%\${searchParams.q}%\`);
  if (searchParams?.minPrice) query = query.gte('price', searchParams.minPrice);
  if (searchParams?.maxPrice) query = query.lte('price', searchParams.maxPrice);
  if (searchParams?.city) query = query.eq('city', searchParams.city);
  if (searchParams?.category) {
      const slug = searchParams.category;
      if (slug === 'emlak') query = query.or('category.ilike.konut%,category.ilike.isyeri%,category.ilike.arsa%');
      else if (slug === 'konut') query = query.ilike('category', 'konut%');
      else if (slug === 'is-yeri') query = query.ilike('category', 'isyeri%');
      else if (slug === 'vasita') query = query.or('category.eq.otomobil,category.eq.suv,category.eq.motosiklet');
      else query = query.eq('category', slug);
  }
  if (searchParams?.sort === 'price_asc') query = query.order('price', { ascending: true });
  else if (searchParams?.sort === 'price_desc') query = query.order('price', { ascending: false });
  else query = query.order('created_at', { ascending: false });

  query = query.range(from, to);
  const { data, count, error } = await query;

  if (error) return { data: [], count: 0, totalPages: 0 };
  return { data: data || [], count: count || 0, totalPages: count ? Math.ceil(count / limit) : 0 };
}

// --- CREATE AD (GÜVENLİ VE LOGLU) ---
export async function createAdAction(formData: any) {
  const supabase = await createClient()
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) return { error: 'Oturum açmanız gerekiyor.' }

  // 1. Rate Limit Kontrolü
  const canCreate = await checkRateLimit(user.id, 'ad_creation');
  if (!canCreate) {
      // Spam girişimi logla
      await logActivity(user.id, 'SPAM_AD_CREATION', { reason: 'Rate limit exceeded' });
      return { error: 'Günlük ilan verme limitine (5 adet) ulaştınız.' };
  }

  const validation = adSchema.safeParse(formData);
  if (!validation.success) return { error: validation.error.issues[0].message };

  const { data: profile } = await supabase.from('profiles').select('id').eq('id', user.id).single();
  if (!profile) await supabase.from('profiles').insert([{ id: user.id, email: user.email }]);

  const { data, error } = await supabase.from('ads').insert([{
    ...validation.data,
    user_id: user.id,
    status: 'onay_bekliyor',
    is_vitrin: false,
    is_urgent: false
  }]).select('id').single()

  if (error) return { error: 'Veritabanı hatası.' }

  // 2. Başarılı işlem logu
  await logActivity(user.id, 'CREATE_AD', { adId: data.id, title: validation.data.title });

  revalidatePath('/');
  return { success: true, adId: data.id }
}

export async function getInfiniteAdsAction(page = 1, limit = 20) {
    const supabase = await createClient();
    const start = (page - 1) * limit;
    const end = start + limit - 1;
    const { data, count } = await supabase.from('ads').select('*, profiles(full_name)', { count: 'exact' }).eq('status', 'yayinda').order('created_at', { ascending: false }).range(start, end);
    return { data: data || [], total: count || 0, hasMore: (count || 0) > end + 1 };
}

export async function getAdDetailServer(id: number) {
  const supabase = await createClient()
  const { data } = await supabase.from('ads').select('*, profiles(*), categories(title)').eq('id', id).single()
  return data
}

export async function updateAdAction(id: number, formData: any) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Giriş yapmalısınız' }

    const { error } = await supabase.from('ads').update({ ...formData, status: 'onay_bekliyor' }).eq('id', id).eq('user_id', user.id)
    if (error) return { error: error.message }

    await logActivity(user.id, 'UPDATE_AD', { adId: id });

    revalidatePath('/bana-ozel/ilanlarim')
    return { success: true }
}

export async function activateDopingAction(adId: number, dopingTypes: string[]) {
  const supabase = await createClient();
  const { data: { user } } = await supabase.auth.getUser();
  const updates: any = {};
  if (dopingTypes.includes('1')) updates.is_vitrin = true;
  if (dopingTypes.includes('2')) updates.is_urgent = true;

  const { error } = await supabase.from('ads').update(updates).eq('id', adId);
  if (error) return { error: error.message };

  if (user) await logActivity(user.id, 'ACTIVATE_DOPING', { adId, types: dopingTypes });

  revalidatePath('/');
  return { success: true };
}

export async function createReportAction(adId: number, reason: string, description: string) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { error: 'Giriş yapmalısınız.' };
    const { error } = await supabase.from('reports').insert([{
        ad_id: adId, user_id: user.id, reason, description, status: 'pending'
    }]);
    if (error) return { error: 'Şikayetiniz iletilemedi.' };
    return { success: true };
}

export async function getStoreBySlugServer(slug: string) {
    const supabase = await createClient()
    const { data } = await supabase.from('stores').select('*').eq('slug', slug).single()
    return data
}

export async function getStoreAdsServer(userId: string) {
    const supabase = await createClient()
    const { data } = await supabase.from('ads').select('*').eq('user_id', userId).eq('status', 'yayinda')
    return data || []
}

export async function createStoreAction(formData: any) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Giriş yapmalısınız' }
    const { error } = await supabase.from('stores').insert([{ ...formData, user_id: user.id }])
    if (error) return { error: error.message }
    await supabase.from('profiles').update({ role: 'store' }).eq('id', user.id)

    await logActivity(user.id, 'CREATE_STORE', { name: formData.name });

    revalidatePath('/bana-ozel/magazam')
    return { success: true }
}

export async function updateStoreAction(formData: any) {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if (!user) return { error: 'Giriş yapmalısınız' }
    const { error } = await supabase.from('stores').update(formData).eq('user_id', user.id)
    if (error) return { error: error.message }

    await logActivity(user.id, 'UPDATE_STORE', { name: formData.name });

    revalidatePath('/bana-ozel/magazam')
    return { success: true }
}

export async function getMyStoreServer() {
    const supabase = await createClient()
    const { data: { user } } = await supabase.auth.getUser()
    if(!user) return null
    const { data } = await supabase.from('stores').select('*').eq('user_id', user.id).single()
    return data
}

export async function getAdminStatsServer() {
    const supabase = await createClient();
    const [users, ads, revenue] = await Promise.all([
        supabase.from('profiles').select('*', { count: 'exact', head: true }),
        supabase.from('ads').select('*', { count: 'exact', head: true }).eq('status', 'yayinda'),
        supabase.from('ads').select('*', { count: 'exact', head: true }).or('is_vitrin.eq.true,is_urgent.eq.true')
    ]);
    const estimatedRevenue = (revenue.count || 0) * 100;
    return { totalUsers: users.count || 0, activeAds: ads.count || 0, totalRevenue: estimatedRevenue };
}

export async function getPageBySlugServer(slug: string) {
  const contentMap: any = {
      'hakkimizda': { title: 'Hakkımızda', content: '<p>Sahibinden klon projesi...</p>' },
      'kullanim-kosullari': { title: 'Kullanım Koşulları', content: '<p>Koşullar...</p>' },
      'gizlilik-politikasi': { title: 'Gizlilik Politikası', content: '<p>Gizlilik...</p>' },
  };
  return contentMap[slug] || null;
}

export async function getHelpContentServer() {
  return {
      categories: [{id: 1, title: 'Üyelik', description: 'Giriş işlemleri'}],
      faqs: [{id: 1, question: 'Şifremi unuttum?', answer: 'Şifremi unuttum linkine tıklayın.'}]
  };
}

export async function getAdsByIds(ids: number[]) {
    if (!ids || ids.length === 0) return [];
    const supabase = await createClient();
    const { data } = await supabase.from('ads').select('*, profiles(full_name)').in('id', ids);
    return data || [];
}

export async function getShowcaseAdsServer() {
  const supabase = await createClient()
  const { data } = await supabase.from('ads').select('*').eq('status', 'yayinda').eq('is_vitrin', true).limit(20)
  return data || []
}

export async function getAdminAdsClient() {
  const supabase = await createClient();
  const { data } = await supabase.from('ads').select('*, profiles(full_name)').order('created_at', { ascending: false });
  return data || [];
}

export async function approveAdAction(adId: number) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    const { error } = await supabase.from('ads').update({ status: 'yayinda' }).eq('id', adId);
    if(error) return { error: error.message };

    if (user) await logActivity(user.id, 'ADMIN_APPROVE_AD', { adId });

    revalidatePath('/admin/ilanlar');
    return { success: true };
}

export async function rejectAdAction(adId: number, reason: string) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();

    const { error } = await supabase.from('ads').update({ status: 'reddedildi' }).eq('id', adId);
    if(error) return { error: error.message };

    if (user) await logActivity(user.id, 'ADMIN_REJECT_AD', { adId, reason });

    revalidatePath('/admin/ilanlar');
    return { success: true };
}

export async function getAdFavoriteCount(adId: number) {
    const supabase = await createClient();
    const { count } = await supabase.from('favorites').select('*', { count: 'exact', head: true }).eq('ad_id', adId);
    return count || 0;
}

export async function updateProfileAction(formData: any) {
    const supabase = await createClient();
    const { data: { user } } = await supabase.auth.getUser();
    if (!user) return { error: 'Oturum açmanız gerekiyor.' };
    const updates = { full_name: formData.full_name, phone: formData.phone, avatar_url: formData.avatar_url, updated_at: new Date().toISOString() };
    const { error } = await supabase.from('profiles').update(updates).eq('id', user.id);
    if (error) return { error: error.message };

    await logActivity(user.id, 'UPDATE_PROFILE', {});

    revalidatePath('/bana-ozel/ayarlar');
    return { success: true };
}

export async function updatePasswordAction(password: string) {
    const supabase = await createClient();
    const { error } = await supabase.auth.updateUser({ password: password });
    if (error) return { error: error.message };
    return { success: true };
}

export async function getRelatedAdsServer(category: string, currentId: number, basePrice?: number) {
    const supabase = await createClient();
    let query = supabase.from('ads').select('*').eq('category', category).eq('status', 'yayinda').neq('id', currentId);
    if (basePrice) {
        const minPrice = basePrice * 0.7;
        const maxPrice = basePrice * 1.3;
        query = query.gte('price', minPrice).lte('price', maxPrice);
    }
    const { data } = await query.limit(5);
    return data || [];
}

export async function incrementViewCountAction(adId: number) {
    const supabase = await createClient();
    await supabase.rpc('increment_view_count', { ad_id_input: adId });
}

// --- AUDIT LOG FETCHER (ADMIN) ---
export async function getAuditLogsServer() {
    const supabase = await createClient();
    const { data } = await supabase
        .from('audit_logs')
        .select('*, profiles:user_id(full_name, email)')
        .order('created_at', { ascending: false })
        .limit(100);
    return data || [];
}
`;
writeFile("lib/actions.ts", actionsContent);

// =============================================================================
// 5. APP/ADMIN/LOGS/PAGE.TSX (LOG İZLEME EKRANI)
// =============================================================================
const logsPageContent = `
import React from 'react';
import { getAuditLogsServer } from '@/lib/actions';
import { ScrollText, User, Clock, AlertCircle } from 'lucide-react';

export default async function AdminLogsPage() {
  const logs = await getAuditLogsServer();

  return (
    <div className="space-y-6">
      <div className="flex justify-between items-center">
        <h1 className="text-2xl font-bold text-gray-800 flex items-center gap-2">
            <ScrollText size={24} className="text-blue-600" /> Sistem Kayıtları (Audit Logs)
        </h1>
        <span className="text-xs text-gray-500 bg-gray-100 px-3 py-1 rounded-full">Son 100 işlem</span>
      </div>

      <div className="bg-white rounded-lg shadow-sm border border-gray-200 overflow-hidden">
        <table className="w-full text-left text-sm">
            <thead className="bg-gray-50 border-b text-gray-500 uppercase text-xs">
                <tr>
                    <th className="p-4">Kullanıcı</th>
                    <th className="p-4">İşlem (Action)</th>
                    <th className="p-4">Detaylar (Metadata)</th>
                    <th className="p-4 text-right">Zaman</th>
                </tr>
            </thead>
            <tbody className="divide-y divide-gray-100">
                {logs.length === 0 ? (
                    <tr><td colSpan={4} className="p-8 text-center text-gray-500">Henüz kayıt yok.</td></tr>
                ) : (
                    logs.map((log: any) => (
                        <tr key={log.id} className="hover:bg-gray-50 transition-colors">
                            <td className="p-4">
                                <div className="flex items-center gap-2">
                                    <User size={16} className="text-gray-400"/>
                                    <div className="flex flex-col">
                                        <span className="font-bold text-gray-700">{log.profiles?.full_name || 'Bilinmiyor'}</span>
                                        <span className="text-[10px] text-gray-400">{log.profiles?.email}</span>
                                    </div>
                                </div>
                            </td>
                            <td className="p-4">
                                <span className={\`px-2 py-1 rounded text-[10px] font-bold font-mono \${
                                    log.action.includes('ADMIN') ? 'bg-purple-100 text-purple-700' :
                                    log.action.includes('CREATE') ? 'bg-green-100 text-green-700' :
                                    log.action.includes('SPAM') ? 'bg-red-100 text-red-700' :
                                    'bg-blue-100 text-blue-700'
                                }\`}>
                                    {log.action}
                                </span>
                            </td>
                            <td className="p-4 text-xs font-mono text-gray-600 max-w-[300px] truncate">
                                {JSON.stringify(log.metadata)}
                            </td>
                            <td className="p-4 text-right text-xs text-gray-500">
                                <div className="flex items-center justify-end gap-1">
                                    <Clock size={12}/>
                                    {new Date(log.created_at).toLocaleString('tr-TR')}
                                </div>
                            </td>
                        </tr>
                    ))
                )}
            </tbody>
        </table>
      </div>
    </div>
  );
}
`;
writeFile("app/admin/logs/page.tsx", logsPageContent);

// =============================================================================
// 6. COMPONENTS/ADMINSIDEBAR.TSX (LINK EKLENİYOR)
// =============================================================================
const adminSidebarContent = `
"use client";
import React from 'react';
import Link from 'next/link';
import { usePathname } from 'next/navigation';
import { LayoutDashboard, FileText, Users, DollarSign, Settings, LogOut, ExternalLink, ScrollText } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';

const menuItems = [
  { name: 'Genel Bakış', href: '/admin', icon: LayoutDashboard },
  { name: 'İlan Yönetimi', href: '/admin/ilanlar', icon: FileText },
  { name: 'Kullanıcılar', href: '/admin/kullanicilar', icon: Users },
  { name: 'Ödemeler & Ciro', href: '/admin/odemeler', icon: DollarSign },
  { name: 'Sistem Logları', href: '/admin/logs', icon: ScrollText }, // YENİ
  { name: 'Ayarlar', href: '/admin/ayarlar', icon: Settings },
];

export default function AdminSidebar() {
  const pathname = usePathname();
  const { logout } = useAuth();

  return (
    <aside className="w-64 bg-[#1a202c] text-white flex flex-col h-screen shrink-0 sticky top-0 overflow-y-auto">
      <div className="p-6 border-b border-gray-700 flex items-center justify-between">
        <span className="font-bold text-xl tracking-tight">Admin<span className="text-[#ffe800]">Panel</span></span>
      </div>

      <nav className="flex-1 p-4 space-y-1">
        {menuItems.map((item) => {
          const isActive = pathname === item.href;
          return (
            <Link
              key={item.href}
              href={item.href}
              className={\`flex items-center gap-3 px-4 py-3 rounded-md transition-colors \${isActive ? 'bg-blue-600 text-white' : 'text-gray-400 hover:bg-gray-800 hover:text-white'}\`}
            >
              <item.icon size={20} />
              <span className="text-sm font-medium">{item.name}</span>
            </Link>
          );
        })}
      </nav>

      <div className="p-4 border-t border-gray-700 space-y-2">
        <Link href="/" target="_blank" className="flex items-center gap-3 px-4 py-2 text-gray-400 hover:text-white text-sm">
          <ExternalLink size={16} /> Siteye Git
        </Link>
        <button
          onClick={() => logout()}
          className="w-full flex items-center gap-3 px-4 py-2 text-red-400 hover:text-red-300 text-sm hover:bg-gray-800 rounded"
        >
          <LogOut size={16} /> Çıkış Yap
        </button>
      </div>
    </aside>
  );
}
`;
writeFile("components/AdminSidebar.tsx", adminSidebarContent);

console.log(
  colors.green +
    "\\n✅ SENIOR UPGRADE TAMAMLANDI! Artık sisteminizde Loglama ve Rate Limit koruması var." +
    "\\n⚠️ ÖNEMLİ: 'supabase/audit.sql' dosyasındaki kodu Supabase SQL Editor'de çalıştırmayı unutmayın!" +
    colors.reset,
);
