const fs = require("fs");
const path = require("path");

const colors = {
  reset: "\x1b[0m",
  green: "\x1b[32m",
  blue: "\x1b[34m",
  red: "\x1b[31m",
  yellow: "\x1b[33m",
  bold: "\x1b[1m",
};

console.log(
  colors.blue +
    colors.bold +
    "\n💬 MESSAGING SYSTEM OVERHAUL: SENIOR DEV EDITION\n" +
    colors.reset,
);

function writeFile(filePath, content) {
  try {
    const absolutePath = path.join(__dirname, filePath);
    const dir = path.dirname(absolutePath);
    if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(absolutePath, content.trim());
    console.log(`${colors.green}✔ [ONARILDI]${colors.reset} ${filePath}`);
  } catch (error) {
    console.error(
      `${colors.red}✘ [HATA]${colors.reset} ${filePath}: ${error.message}`,
    );
  }
}

// =============================================================================
// 1. DATABASE SCHEMA (CRITICAL SQL)
// =============================================================================
// Senior Note: Mesajlaşma için sağlam bir veritabanı yapısı şart.
// Conversations tablosu "Tekil" (Unique) olmalı, yani aynı ilanda aynı iki kişi arasında
// sadece 1 sohbet olabilir. Bunu SQL ile garanti altına alıyoruz.

const messagingSqlContent = `
-- BU KODU SUPABASE SQL EDITOR EKRANINDA ÇALIŞTIRIN --

-- 1. Sohbetler Tablosu (Conversations)
create table if not exists conversations (
  id bigint generated by default as identity primary key,
  ad_id bigint references ads(id) not null,
  buyer_id uuid references auth.users not null,
  seller_id uuid references auth.users not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null,

  -- Aynı ilan için aynı alıcı ve satıcı arasında tek bir sohbet olabilir
  unique(ad_id, buyer_id, seller_id)
);

-- 2. Mesajlar Tablosu (Messages)
create table if not exists messages (
  id bigint generated by default as identity primary key,
  conversation_id bigint references conversations(id) on delete cascade not null,
  sender_id uuid references auth.users not null,
  content text not null,
  is_read boolean default false,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 3. RLS (Row Level Security) Politikaları - GÜVENLİK İÇİN KRİTİK
alter table conversations enable row level security;
alter table messages enable row level security;

-- Sohbetleri sadece katılımcıları görebilir
create policy "Users can view their own conversations"
  on conversations for select
  using (auth.uid() = buyer_id or auth.uid() = seller_id);

create policy "Users can insert conversations"
  on conversations for insert
  with check (auth.uid() = buyer_id);

-- Mesajları sadece sohbetin katılımcıları görebilir (JOIN ile kontrol)
create policy "Users can view messages in their conversations"
  on messages for select
  using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

create policy "Users can insert messages"
  on messages for insert
  with check (auth.uid() = sender_id);

create policy "Users can update read status"
  on messages for update
  using (
    exists (
      select 1 from conversations c
      where c.id = messages.conversation_id
      and (c.buyer_id = auth.uid() or c.seller_id = auth.uid())
    )
  );

-- 4. Realtime Yayın
alter publication supabase_realtime add table messages;
alter publication supabase_realtime add table conversations;
`;

writeFile("supabase/messaging_fix.sql", messagingSqlContent);

// =============================================================================
// 2. SERVICE LAYER FIX (LIB/SERVICES.TS)
// =============================================================================
// Senior Note: Stub fonksiyonları kaldırıp gerçek Supabase sorgularını yazıyoruz.
// startConversationClient artık önce "Böyle bir sohbet var mı?" diye bakıyor.

const servicesContent = `
import { createClient } from '@/lib/supabase/client'

const supabase = createClient()

// --- MESAJLAŞMA SİSTEMİ (FIXED) ---

export async function getConversationsClient(userId: string) {
  const { data, error } = await supabase
    .from('conversations')
    .select('*, ads(id, title, image, price, currency, city, district), profiles:buyer_id(full_name, avatar_url), seller:seller_id(full_name, avatar_url)')
    .or(\`buyer_id.eq.\${userId},seller_id.eq.\${userId}\`)
    .order('updated_at', { ascending: false });
  if (error) {
      console.error("Get Conversations Error:", error);
      return [];
  }
  return data || [];
}

export async function getMessagesClient(conversationId: number) {
  const { data, error } = await supabase
    .from('messages')
    .select('*')
    .eq('conversation_id', conversationId)
    .order('created_at', { ascending: true });

  if (error) console.error("Get Messages Error:", error);
  return data || [];
}

export async function sendMessageClient(conversationId: number, senderId: string, content: string) {
  // 1. Mesajı kaydet
  const { data, error } = await supabase
    .from('messages')
    .insert([{ conversation_id: conversationId, sender_id: senderId, content }])
    .select()
    .single();

  // 2. Sohbetin 'updated_at' zamanını güncelle (Listede yukarı çıksın diye)
  if (!error) {
      await supabase.from('conversations')
        .update({ updated_at: new Date().toISOString() })
        .eq('id', conversationId);
  }

  return { data, error };
}

export async function startConversationClient(adId: number, buyerId: string, sellerId: string) {
    // 1. Önce mevcut sohbet var mı kontrol et
    const { data: existingConv, error: fetchError } = await supabase
        .from('conversations')
        .select('id')
        .eq('ad_id', adId)
        .eq('buyer_id', buyerId)
        .eq('seller_id', sellerId)
        .single();

    if (existingConv) {
        return { data: existingConv, error: null };
    }

    // 2. Yoksa yeni oluştur
    const { data: newConv, error: createError } = await supabase
        .from('conversations')
        .insert([{ ad_id: adId, buyer_id: buyerId, seller_id: sellerId }])
        .select()
        .single();

    return { data: newConv, error: createError };
}

export async function markMessagesAsReadClient(conversationId: number, userId: string) {
  // Sadece karşı tarafın gönderdiği okunmamış mesajları güncelle
  return await supabase
    .from('messages')
    .update({ is_read: true })
    .eq('conversation_id', conversationId)
    .neq('sender_id', userId)
    .eq('is_read', false);
}

// --- DİĞER SERVİSLER (MEVCUT YAPIDAN KORUNDU) ---
// (Bu kısım önceki kodların çalışmaya devam etmesi için gerekli temel servisleri içerir)

export async function getUserAdsClient(userId: string) {
  const { data } = await supabase.from('ads').select('*').eq('user_id', userId).order('created_at', { ascending: false });
  return data || [];
}

export async function updateAdStatusClient(id: number, status: string) {
  return await supabase.from('ads').update({ status }).eq('id', id);
}

export async function toggleFavoriteClient(userId: string, adId: number) {
  const { data } = await supabase.from('favorites').select('id').eq('user_id', userId).eq('ad_id', adId).single()
  if (data) { await supabase.from('favorites').delete().eq('id', data.id); return false; }
  else { await supabase.from('favorites').insert([{ user_id: userId, ad_id: adId }]); return true; }
}

export async function getFavoritesClient(userId: string) {
    const { data } = await supabase.from('favorites').select('ad_id, ads(*)').eq('user_id', userId)
    return data ? data.filter((i: any) => i.ads).map((i: any) => i.ads) : [];
}

export async function getProfileClient(userId: string) {
  const { data } = await supabase.from('profiles').select('*').eq('id', userId).single()
  return data
}

export async function getReviewsClient(targetId: string) {
  const { data } = await supabase.from('reviews').select('*, reviewer:reviewer_id(full_name, avatar_url)').eq('target_id', targetId).order('created_at', { ascending: false });
  return data || [];
}

export async function addReviewClient(targetId: string, rating: number, comment: string, reviewerId: string) {
  if (targetId === reviewerId) return { error: { message: 'Kendinize yorum yapamazsınız.' } };
  return await supabase.from('reviews').insert([{ target_id: targetId, reviewer_id: reviewerId, rating, comment }]);
}

export async function getSavedSearchesClient(userId: string) {
  const { data } = await supabase.from('saved_searches').select('*').eq('user_id', userId).order('created_at', { ascending: false });
  return data || [];
}

export async function deleteSavedSearchClient(id: number) {
  return await supabase.from('saved_searches').delete().eq('id', id);
}

export async function getAllUsersClient() {
  const { data } = await supabase.from('profiles').select('*').order('created_at', { ascending: false });
  return data || [];
}

export async function updateUserStatusClient(userId: string, status: string) {
  return await supabase.from('profiles').update({ status }).eq('id', userId);
}

export async function updateUserRoleClient(userId: string, role: string) {
  return await supabase.from('profiles').update({ role }).eq('id', userId);
}

export async function getAdminAdsClient() {
  const { data } = await supabase.from('ads').select('*, profiles(full_name)').order('created_at', { ascending: false });
  return data || [];
}

export async function getAdsClient(searchParams?: any) {
  let query = supabase.from('ads').select('id, title, price, currency').eq('status', 'yayinda');
  if (searchParams?.q) query = query.ilike('title', \`%\${searchParams.q}%\`);
  const { data } = await query.limit(5);
  return data || [];
}

export async function uploadImageClient(file: File) {
  const fileExt = file.name.split('.').pop();
  const fileName = \`\${Date.now()}-\${Math.random().toString(36).substring(2, 9)}.\${fileExt}\`;
  const { data, error } = await supabase.storage.from('ads').upload(fileName, file);
  if (error) throw error;
  return supabase.storage.from('ads').getPublicUrl(fileName).data.publicUrl;
}

export async function getNotificationsClient(userId: string) {
  const { data } = await supabase.from('notifications').select('*').eq('user_id', userId).order('created_at', { ascending: false }).limit(20);
  return data || [];
}
export async function markNotificationReadClient(id: number) {
  await supabase.from('notifications').update({ is_read: true }).eq('id', id);
}
export async function markAllNotificationsReadClient(userId: string) {
  await supabase.from('notifications').update({ is_read: true }).eq('user_id', userId);
}
export async function createNotificationClient(userId: string, title: string, message: string) {
  await supabase.from('notifications').insert([{ user_id: userId, title, message }]);
}
`;

writeFile("lib/services.ts", servicesContent);

// =============================================================================
// 3. UI INTEGRATION FIX (SELLER SIDEBAR)
// =============================================================================
// Senior Note: Butona tıklandığında loading state göstermeli ve hata varsa kullanıcıyı uyarmalı.

const sellerSidebarContent = `
"use client";
import React, { useState, useEffect } from 'react';
import Link from 'next/link';
import { Phone, ShieldCheck, User, MessageCircle, Star, Send, Loader2 } from 'lucide-react';
import { useAuth } from '@/context/AuthContext';
import { startConversationClient } from '@/lib/services';
import { useRouter } from 'next/navigation';
import { useToast } from '@/context/ToastContext';
import { getSellerReviewsServer, createReviewAction } from '@/lib/actions';

export default function SellerSidebar({ sellerId, sellerName, sellerPhone, adId }: any) {
  const { user } = useAuth();
  const router = useRouter();
  const { addToast } = useToast();
  const [showPhone, setShowPhone] = useState(false);
  const [ratingData, setRatingData] = useState({ avg: 0, count: 0 });
  const [isMsgLoading, setIsMsgLoading] = useState(false);

  useEffect(() => {
    async function fetchReviews() {
        const reviews = await getSellerReviewsServer(sellerId);
        if (reviews.length > 0) {
            const total = reviews.reduce((sum: number, r: any) => sum + r.rating, 0);
            setRatingData({ avg: total / reviews.length, count: reviews.length });
        }
    }
    fetchReviews();
  }, [sellerId]);

  const handleSendMessage = async () => {
    if (!user) {
        addToast('Mesaj göndermek için giriş yapmalısınız.', 'info');
        router.push('/login');
        return;
    }

    if (user.id === sellerId) {
        addToast('Kendi ilanınıza mesaj gönderemezsiniz.', 'warning');
        return;
    }

    setIsMsgLoading(true);
    try {
        // Gerçek API Çağrısı
        const { data, error } = await startConversationClient(adId, user.id, sellerId);

        if(error) {
            console.error(error);
            addToast('Sohbet başlatılamadı. Lütfen tekrar deneyin.', 'error');
        } else if (data) {
            router.push(\`/bana-ozel/mesajlarim?convId=\${data.id}\`);
        }
    } catch (err) {
        addToast('Beklenmedik bir hata oluştu.', 'error');
    } finally {
        setIsMsgLoading(false);
    }
  };

  return (
    <div className="bg-white rounded-xl shadow-card border border-gray-100 p-6">
      {/* Profil Başlığı */}
      <div className="flex items-center gap-4 mb-6">
        <div className="w-14 h-14 bg-indigo-50 rounded-full flex items-center justify-center border-2 border-white shadow-sm text-indigo-600">
           <User size={28} />
        </div>
        <div>
           <h3 className="font-bold text-slate-900 text-lg">{sellerName}</h3>
           <Link href={\`/satici/\${sellerId}\`} className="text-xs text-indigo-600 font-medium hover:underline flex items-center gap-1">
             Satıcının Tüm İlanları
           </Link>
        </div>
      </div>

      {/* Puan */}
      <div className="mb-6 bg-slate-50 p-3 rounded-lg flex justify-between items-center">
         <div className="flex text-yellow-400 gap-0.5">
            {[...Array(5)].map((_,i) => <Star key={i} size={16} fill={i < Math.round(ratingData.avg) ? "currentColor" : "none"} />)}
         </div>
         <span className="text-sm font-bold text-slate-700">{ratingData.avg.toFixed(1)} <span className="text-slate-400 font-normal">({ratingData.count})</span></span>
      </div>

      {/* Aksiyonlar */}
      <div className="space-y-3">
        <div className="rounded-lg overflow-hidden border border-slate-200">
            {!showPhone ? (
                <button onClick={() => setShowPhone(true)} className="w-full bg-slate-100 hover:bg-slate-200 py-3.5 flex items-center justify-center gap-2 text-slate-700 font-bold transition-colors">
                    <Phone size={18} /> Telefonu Göster
                </button>
            ) : (
                <div className="bg-green-50 py-3.5 text-center text-green-700 font-bold text-lg select-all border-green-100">
                    {sellerPhone}
                </div>
            )}
        </div>

        <button
            onClick={handleSendMessage}
            disabled={isMsgLoading}
            className="w-full bg-indigo-600 text-white hover:bg-indigo-700 py-3.5 rounded-lg font-bold flex items-center justify-center gap-2 transition-all shadow-md shadow-indigo-100 disabled:opacity-70"
        >
            {isMsgLoading ? <Loader2 size={18} className="animate-spin" /> : <MessageCircle size={18} />}
            Mesaj Gönder
        </button>
      </div>

      <div className="mt-6 pt-4 border-t border-slate-100 flex items-center justify-center gap-2 text-xs text-slate-500">
         <ShieldCheck size={14} className="text-green-500"/> Hesap Onaylı
      </div>
    </div>
  );
}
`;

writeFile("components/SellerSidebar.tsx", sellerSidebarContent);

console.log(colors.green + "\n✅ MESAJLAŞMA SİSTEMİ ONARILDI." + colors.reset);
console.log(
  colors.yellow + "⚠ DİKKAT: SQL'i Çalıştırmayı Unutmayın!" + colors.reset,
);
console.log(
  "Supabase Dashboard -> SQL Editor kısmına gidin ve 'supabase/messaging_fix.sql' dosyasının içeriğini yapıştırıp çalıştırın.",
);
console.log(
  "Bu işlem veritabanı tablolarını oluşturacak ve mesajlaşmayı aktif hale getirecektir.",
);
